#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := ESP_MeteoStation

include $(IDF_PATH)/make/project.mk
EXTRA_COMPONENT_DIRS := $(CURDIR)/components
